# -*- coding: utf-8 -*-
"""Resumodetexto.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YlUYU5_WqP5LZyi7XwDyUNNT9c62KvX5
"""

!pip install -U -q google-generativeai

!pip install google-generativeai

pip install python-dotenv

!pip install transformers

from transformers import pipeline

summarizer = pipeline("summarization")

texto = """
Este é um exemplo de texto longo que você deseja resumir.
Ele pode conter vários parágrafos e discutir diferentes tópicos.
O objetivo é usar o modelo de resumo para extrair os pontos principais e criar um resumo conciso do texto.
"""

print(resumo[0]['summary_text'])

print(resumo[0]['summary_text'])

texto = input("Cole o texto que você quer resumir aqui:\n")

resumo = summarizer(texto, do_sample=False)

print("\nResumo do texto:\n")
print(resumo[0]['summary_text'])

!pip install transformers gTTS
from transformers import pipeline
from gtts import gTTS
from IPython.display import Audio

summarizer = pipeline("summarization", model="facebook/bart-large-cnn")

texto = input("Cole o texto que você quer resumir aqui:\n")
resumo = summarizer(texto, do_sample=False)

texto_resumido = resumo[0]['summary_text']
print("\nResumo do texto:\n", texto_resumido)

# Converter o texto em áudio
tts = gTTS(text=texto_resumido, lang='pt')
tts.save("resumo.mp3")

# Reproduzir o áudio
display(Audio("resumo.mp3", autoplay=True))